"""First migration

Revision ID: c6f1226eb52b
Revises: 
Create Date: 2024-08-31 09:00:40.714264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f1226eb52b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('sum_quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_by_sizes', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('nm_id')
    )
    op.create_index(op.f('ix_product_nm_id'), 'product', ['nm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_nm_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
